/**
 * Form Schema — shared types for AI-generated form templates
 *
 * A FormSchema is the structured representation of a .docx inspection form
 * template, generated by MiMo V2.5 and editable by admins before saving.
 */

/** Field types available in dynamic forms */
export type FormFieldType =
  | "text"       // short text input
  | "number"     // numeric input
  | "select"     // dropdown / single-choice
  | "yesno"      // YES / NO toggle
  | "date"       // date picker
  | "textarea"   // multi-line text
  | "signature"  // signature line
  | "section"    // sub-section header (non-editable)
  | "table"      // repeating row table (for checklist-type forms)
  | "image";     // image attachment / screenshot

/** A single form field definition */
export interface FormField {
  /** Unique key within the section (snake_case, e.g. "polymer_name") */
  key: string;
  /** Display label (e.g. "Polymer Name") */
  label: string;
  /** Field type */
  type: FormFieldType;
  /** Whether this field is required */
  required: boolean;
  /** Placeholder / hint text */
  placeholder?: string;
  /** Default value */
  default_value?: string | number | boolean;
  /** Options for select type */
  options?: string[];
  /** Numeric validation */
  min?: number;
  max?: number;
  /** Unit suffix (e.g. "bar", "C", "kN") */
  unit?: string;
  /** Whether this field is pre-filled by AI from the template */
  prefill_from_template?: string;
}

/** A section/group of fields in the form */
export interface FormSection {
  /** Section title (e.g. "Process Equipment Details") */
  title: string;
  /** Section description / subheading */
  description?: string;
  /** Fields in this section */
  fields: FormField[];
}

/** The complete form schema generated from a .docx template */
export interface FormSchema {
  /** Form title (e.g. "Top Part QC Inspection Report") */
  form_title: string;
  /** Document / form number (e.g. "QC_01-Top") */
  form_number?: string;
  /** Revision number if present */
  revision?: string;
  /** Sections of fields */
  sections: FormSection[];
  /** Overall metadata */
  metadata?: {
    /** Part name detected in the document */
    part_name?: string;
    /** Equipment name detected */
    equipment_name?: string;
    /** Any default tolerance found */
    default_tolerance?: number;
  };
}

/**
 * Upload + generation status for the DOCX upload dialog
 */
export type GenerateStatus =
  | "idle"
  | "uploading"
  | "processing"
  | "preview"
  | "saving"
  | "done"
  | "error";

/**
 * Payload returned by the AI edge function
 */
export interface GenerateSchemaResult {
  schema: FormSchema;
  raw_text: string;
  model_used: string;
}
