import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { toast } from "sonner";
import { ArrowLeft, Loader2 } from "lucide-react";

import { supabase } from "@/integrations/supabase/client";
import { PageHeader } from "@/components/inventory/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { FileUpload } from "@/components/inventory/file-upload";
import { TRAINING_PERSONNEL, TRAINING_SCHEDULES } from "@/lib/inventory/employees";

export const Route = createFileRoute("/_authenticated/roles/training/new")({
  ssr: false,
  component: TrainingNewPage,
});

function TrainingNewPage() {
  const navigate = useNavigate();
  const qc = useQueryClient();
  const [name, setName] = useState("");
  const [objectives, setObjectives] = useState("");
  const [duration, setDuration] = useState("");
  const [trainer, setTrainer] = useState("");
  const [trainees, setTrainees] = useState<string[]>([]);
  const [status, setStatus] = useState("Active");
  const [evaluation, setEvaluation] = useState("");
  const [schedule, setSchedule] = useState("");
  const [documents, setDocuments] = useState<string[]>([]);

  const { mutate, isPending } = useMutation({
    mutationFn: async () => {
      const { error } = await supabase.from("training_programs").insert({
        training_name: name,
        training_objectives: objectives || null,
        training_duration: duration || null,
        trainer,
        trainees: trainees.length ? trainees : [],
        status,
        performance_evaluation: evaluation || null,
        schedule,
        documents,
        // training_id auto-generated by trigger
      });
      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Training program created");
      qc.invalidateQueries({ queryKey: ["training_programs"] });
      navigate({ to: "/roles/training" });
    },
    onError: (e: any) => toast.error(e.message ?? "Failed to create training program"),
  });

  const toggleTrainee = (v: string) =>
    setTrainees((prev) => (prev.includes(v) ? prev.filter((x) => x !== v) : [...prev, v]));

  const canSave = name && trainer && schedule && trainees.length > 0;

  return (
    <div>
      <PageHeader
        title="New Training Program"
        description="Add a new training program to the QMS registry"
        actions={
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate({ to: "/roles/training" })}
            className="text-[13px]"
          >
            <ArrowLeft className="h-3.5 w-3.5 mr-1" /> Back to Training
          </Button>
        }
      />

      <Card>
        <CardHeader>
          <CardTitle>Training details</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 max-w-2xl p-6">
          <div>
            <Label className="label-caps">Training Name *</Label>
            <Input
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. Procedure for Risk Management"
              className="mt-1"
            />
          </div>

          <div>
            <Label className="label-caps">Training Objectives</Label>
            <Textarea
              rows={4}
              value={objectives}
              onChange={(e) => setObjectives(e.target.value)}
              className="mt-1"
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label className="label-caps">Training Duration</Label>
              <Input
                value={duration}
                onChange={(e) => setDuration(e.target.value)}
                placeholder="e.g. 1 day"
                className="mt-1"
              />
            </div>
            <div>
              <Label className="label-caps">Status</Label>
              <Select value={status} onValueChange={setStatus}>
                <SelectTrigger className="mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Active">Active</SelectItem>
                  <SelectItem value="Inactive">Inactive</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div>
            <Label className="label-caps">Trainer *</Label>
            <Select value={trainer} onValueChange={setTrainer}>
              <SelectTrigger className="mt-1">
                <SelectValue placeholder="Choose a trainer" />
              </SelectTrigger>
              <SelectContent>
                {TRAINING_PERSONNEL.map((p) => (
                  <SelectItem key={p.value} value={p.value}>
                    {p.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div>
            <Label className="label-caps">Trainees * (multiple)</Label>
            <div className="mt-2 grid grid-cols-2 gap-2 rounded border border-border p-3 max-h-48 overflow-y-auto">
              {TRAINING_PERSONNEL.map((p) => (
                <label key={p.value} className="flex items-center gap-2 text-[13px] cursor-pointer">
                  <Checkbox
                    checked={trainees.includes(p.value)}
                    onCheckedChange={() => toggleTrainee(p.value)}
                  />
                  {p.label}
                </label>
              ))}
            </div>
          </div>

          <div>
            <Label className="label-caps">Schedule *</Label>
            <Select value={schedule} onValueChange={setSchedule}>
              <SelectTrigger className="mt-1">
                <SelectValue placeholder="Choose a schedule" />
              </SelectTrigger>
              <SelectContent>
                {TRAINING_SCHEDULES.map((s) => (
                  <SelectItem key={s.value} value={s.value}>
                    {s.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div>
            <Label className="label-caps">Performance Evaluation Key Factors</Label>
            <Textarea
              rows={4}
              value={evaluation}
              onChange={(e) => setEvaluation(e.target.value)}
              className="mt-1"
            />
          </div>

          <div className="max-w-xl">
            <Label className="label-caps">Documents</Label>
            <FileUpload
              pathPrefix="training"
              onFilesChange={setDocuments}
              existingUrls={documents}
            />
          </div>

          <div className="flex justify-between pt-2">
            <Button variant="outline" onClick={() => navigate({ to: "/roles/training" })}>
              Cancel
            </Button>
            <Button onClick={() => mutate()} disabled={!canSave || isPending}>
              {isPending && <Loader2 className="h-4 w-4 animate-spin mr-2" />}
              Save Training Program
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
