/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedTraceabilityRouteImport } from './routes/_authenticated/traceability'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRawMaterialsRouteImport } from './routes/_authenticated/raw-materials'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProductionPlanningRouteImport } from './routes/_authenticated/production-planning'
import { Route as AuthenticatedProductionNewRouteImport } from './routes/_authenticated/production-new'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedPartsRouteImport } from './routes/_authenticated/parts'
import { Route as AuthenticatedOtherItemsRouteImport } from './routes/_authenticated/other-items'
import { Route as AuthenticatedEquipmentNewRouteImport } from './routes/_authenticated/equipment-new'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBatchRecallRouteImport } from './routes/_authenticated/batch-recall'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedProductsBomIdRouteImport } from './routes/_authenticated/products-bom.$id'
import { Route as AuthenticatedEquipmentEditIdRouteImport } from './routes/_authenticated/equipment-edit.$id'
import { Route as AuthenticatedEquipmentDetailIdRouteImport } from './routes/_authenticated/equipment-detail.$id'
import { Route as AuthenticatedStockHistoryTypeIdRouteImport } from './routes/_authenticated/stock-history.$type.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTraceabilityRoute =
  AuthenticatedTraceabilityRouteImport.update({
    id: '/traceability',
    path: '/traceability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRawMaterialsRoute =
  AuthenticatedRawMaterialsRouteImport.update({
    id: '/raw-materials',
    path: '/raw-materials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionPlanningRoute =
  AuthenticatedProductionPlanningRouteImport.update({
    id: '/production-planning',
    path: '/production-planning',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionNewRoute =
  AuthenticatedProductionNewRouteImport.update({
    id: '/production-new',
    path: '/production-new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartsRoute = AuthenticatedPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOtherItemsRoute = AuthenticatedOtherItemsRouteImport.update({
  id: '/other-items',
  path: '/other-items',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipmentNewRoute =
  AuthenticatedEquipmentNewRouteImport.update({
    id: '/equipment-new',
    path: '/equipment-new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBatchRecallRoute =
  AuthenticatedBatchRecallRouteImport.update({
    id: '/batch-recall',
    path: '/batch-recall',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsBomIdRoute =
  AuthenticatedProductsBomIdRouteImport.update({
    id: '/products-bom/$id',
    path: '/products-bom/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentEditIdRoute =
  AuthenticatedEquipmentEditIdRouteImport.update({
    id: '/equipment-edit/$id',
    path: '/equipment-edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentDetailIdRoute =
  AuthenticatedEquipmentDetailIdRouteImport.update({
    id: '/equipment-detail/$id',
    path: '/equipment-detail/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockHistoryTypeIdRoute =
  AuthenticatedStockHistoryTypeIdRouteImport.update({
    id: '/stock-history/$type/$id',
    path: '/stock-history/$type/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/batch-recall': typeof AuthenticatedBatchRecallRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/equipment-new': typeof AuthenticatedEquipmentNewRoute
  '/other-items': typeof AuthenticatedOtherItemsRoute
  '/parts': typeof AuthenticatedPartsRoute
  '/production': typeof AuthenticatedProductionRoute
  '/production-new': typeof AuthenticatedProductionNewRoute
  '/production-planning': typeof AuthenticatedProductionPlanningRoute
  '/products': typeof AuthenticatedProductsRoute
  '/raw-materials': typeof AuthenticatedRawMaterialsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/traceability': typeof AuthenticatedTraceabilityRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/equipment-detail/$id': typeof AuthenticatedEquipmentDetailIdRoute
  '/equipment-edit/$id': typeof AuthenticatedEquipmentEditIdRoute
  '/products-bom/$id': typeof AuthenticatedProductsBomIdRoute
  '/stock-history/$type/$id': typeof AuthenticatedStockHistoryTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/batch-recall': typeof AuthenticatedBatchRecallRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/equipment-new': typeof AuthenticatedEquipmentNewRoute
  '/other-items': typeof AuthenticatedOtherItemsRoute
  '/parts': typeof AuthenticatedPartsRoute
  '/production': typeof AuthenticatedProductionRoute
  '/production-new': typeof AuthenticatedProductionNewRoute
  '/production-planning': typeof AuthenticatedProductionPlanningRoute
  '/products': typeof AuthenticatedProductsRoute
  '/raw-materials': typeof AuthenticatedRawMaterialsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/traceability': typeof AuthenticatedTraceabilityRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/equipment-detail/$id': typeof AuthenticatedEquipmentDetailIdRoute
  '/equipment-edit/$id': typeof AuthenticatedEquipmentEditIdRoute
  '/products-bom/$id': typeof AuthenticatedProductsBomIdRoute
  '/stock-history/$type/$id': typeof AuthenticatedStockHistoryTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/batch-recall': typeof AuthenticatedBatchRecallRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/equipment-new': typeof AuthenticatedEquipmentNewRoute
  '/_authenticated/other-items': typeof AuthenticatedOtherItemsRoute
  '/_authenticated/parts': typeof AuthenticatedPartsRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/production-new': typeof AuthenticatedProductionNewRoute
  '/_authenticated/production-planning': typeof AuthenticatedProductionPlanningRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/raw-materials': typeof AuthenticatedRawMaterialsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/traceability': typeof AuthenticatedTraceabilityRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/_authenticated/equipment-detail/$id': typeof AuthenticatedEquipmentDetailIdRoute
  '/_authenticated/equipment-edit/$id': typeof AuthenticatedEquipmentEditIdRoute
  '/_authenticated/products-bom/$id': typeof AuthenticatedProductsBomIdRoute
  '/_authenticated/stock-history/$type/$id': typeof AuthenticatedStockHistoryTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alerts'
    | '/batch-recall'
    | '/dashboard'
    | '/equipment'
    | '/equipment-new'
    | '/other-items'
    | '/parts'
    | '/production'
    | '/production-new'
    | '/production-planning'
    | '/products'
    | '/raw-materials'
    | '/reports'
    | '/settings'
    | '/stock'
    | '/traceability'
    | '/vendors'
    | '/equipment-detail/$id'
    | '/equipment-edit/$id'
    | '/products-bom/$id'
    | '/stock-history/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alerts'
    | '/batch-recall'
    | '/dashboard'
    | '/equipment'
    | '/equipment-new'
    | '/other-items'
    | '/parts'
    | '/production'
    | '/production-new'
    | '/production-planning'
    | '/products'
    | '/raw-materials'
    | '/reports'
    | '/settings'
    | '/stock'
    | '/traceability'
    | '/vendors'
    | '/equipment-detail/$id'
    | '/equipment-edit/$id'
    | '/products-bom/$id'
    | '/stock-history/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alerts'
    | '/_authenticated/batch-recall'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipment'
    | '/_authenticated/equipment-new'
    | '/_authenticated/other-items'
    | '/_authenticated/parts'
    | '/_authenticated/production'
    | '/_authenticated/production-new'
    | '/_authenticated/production-planning'
    | '/_authenticated/products'
    | '/_authenticated/raw-materials'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/stock'
    | '/_authenticated/traceability'
    | '/_authenticated/vendors'
    | '/_authenticated/equipment-detail/$id'
    | '/_authenticated/equipment-edit/$id'
    | '/_authenticated/products-bom/$id'
    | '/_authenticated/stock-history/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/traceability': {
      id: '/_authenticated/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof AuthenticatedTraceabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/raw-materials': {
      id: '/_authenticated/raw-materials'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof AuthenticatedRawMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production-planning': {
      id: '/_authenticated/production-planning'
      path: '/production-planning'
      fullPath: '/production-planning'
      preLoaderRoute: typeof AuthenticatedProductionPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production-new': {
      id: '/_authenticated/production-new'
      path: '/production-new'
      fullPath: '/production-new'
      preLoaderRoute: typeof AuthenticatedProductionNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parts': {
      id: '/_authenticated/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof AuthenticatedPartsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/other-items': {
      id: '/_authenticated/other-items'
      path: '/other-items'
      fullPath: '/other-items'
      preLoaderRoute: typeof AuthenticatedOtherItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment-new': {
      id: '/_authenticated/equipment-new'
      path: '/equipment-new'
      fullPath: '/equipment-new'
      preLoaderRoute: typeof AuthenticatedEquipmentNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batch-recall': {
      id: '/_authenticated/batch-recall'
      path: '/batch-recall'
      fullPath: '/batch-recall'
      preLoaderRoute: typeof AuthenticatedBatchRecallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products-bom/$id': {
      id: '/_authenticated/products-bom/$id'
      path: '/products-bom/$id'
      fullPath: '/products-bom/$id'
      preLoaderRoute: typeof AuthenticatedProductsBomIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment-edit/$id': {
      id: '/_authenticated/equipment-edit/$id'
      path: '/equipment-edit/$id'
      fullPath: '/equipment-edit/$id'
      preLoaderRoute: typeof AuthenticatedEquipmentEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment-detail/$id': {
      id: '/_authenticated/equipment-detail/$id'
      path: '/equipment-detail/$id'
      fullPath: '/equipment-detail/$id'
      preLoaderRoute: typeof AuthenticatedEquipmentDetailIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-history/$type/$id': {
      id: '/_authenticated/stock-history/$type/$id'
      path: '/stock-history/$type/$id'
      fullPath: '/stock-history/$type/$id'
      preLoaderRoute: typeof AuthenticatedStockHistoryTypeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedBatchRecallRoute: typeof AuthenticatedBatchRecallRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedEquipmentNewRoute: typeof AuthenticatedEquipmentNewRoute
  AuthenticatedOtherItemsRoute: typeof AuthenticatedOtherItemsRoute
  AuthenticatedPartsRoute: typeof AuthenticatedPartsRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProductionNewRoute: typeof AuthenticatedProductionNewRoute
  AuthenticatedProductionPlanningRoute: typeof AuthenticatedProductionPlanningRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedRawMaterialsRoute: typeof AuthenticatedRawMaterialsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedTraceabilityRoute: typeof AuthenticatedTraceabilityRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
  AuthenticatedEquipmentDetailIdRoute: typeof AuthenticatedEquipmentDetailIdRoute
  AuthenticatedEquipmentEditIdRoute: typeof AuthenticatedEquipmentEditIdRoute
  AuthenticatedProductsBomIdRoute: typeof AuthenticatedProductsBomIdRoute
  AuthenticatedStockHistoryTypeIdRoute: typeof AuthenticatedStockHistoryTypeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedBatchRecallRoute: AuthenticatedBatchRecallRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedEquipmentNewRoute: AuthenticatedEquipmentNewRoute,
  AuthenticatedOtherItemsRoute: AuthenticatedOtherItemsRoute,
  AuthenticatedPartsRoute: AuthenticatedPartsRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProductionNewRoute: AuthenticatedProductionNewRoute,
  AuthenticatedProductionPlanningRoute: AuthenticatedProductionPlanningRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedRawMaterialsRoute: AuthenticatedRawMaterialsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedTraceabilityRoute: AuthenticatedTraceabilityRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
  AuthenticatedEquipmentDetailIdRoute: AuthenticatedEquipmentDetailIdRoute,
  AuthenticatedEquipmentEditIdRoute: AuthenticatedEquipmentEditIdRoute,
  AuthenticatedProductsBomIdRoute: AuthenticatedProductsBomIdRoute,
  AuthenticatedStockHistoryTypeIdRoute: AuthenticatedStockHistoryTypeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
