/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedUdiRegistrationRouteImport } from './routes/_authenticated/udi-registration'
import { Route as AuthenticatedTraceabilityRouteImport } from './routes/_authenticated/traceability'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRegisterUdiRouteImport } from './routes/_authenticated/register-udi'
import { Route as AuthenticatedRawMaterialsRouteImport } from './routes/_authenticated/raw-materials'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProductionPlanningRouteImport } from './routes/_authenticated/production-planning'
import { Route as AuthenticatedProductionNewRouteImport } from './routes/_authenticated/production-new'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedPartsRouteImport } from './routes/_authenticated/parts'
import { Route as AuthenticatedOtherItemsRouteImport } from './routes/_authenticated/other-items'
import { Route as AuthenticatedInspectionFormTemplateRouteImport } from './routes/_authenticated/inspection-form-template'
import { Route as AuthenticatedEquipmentNewRouteImport } from './routes/_authenticated/equipment-new'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedEnquireSerialRouteImport } from './routes/_authenticated/enquire-serial'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBatchRecallRouteImport } from './routes/_authenticated/batch-recall'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedRolesTrainingRouteImport } from './routes/_authenticated/roles.training'
import { Route as AuthenticatedRolesEmployeesRouteImport } from './routes/_authenticated/roles.employees'
import { Route as AuthenticatedProductsBomIdRouteImport } from './routes/_authenticated/products-bom.$id'
import { Route as AuthenticatedProductInspectionProductIdRouteImport } from './routes/_authenticated/product-inspection.$productId'
import { Route as AuthenticatedInspectionFormBatchIdRouteImport } from './routes/_authenticated/inspection-form.$batchId'
import { Route as AuthenticatedEquipmentEditIdRouteImport } from './routes/_authenticated/equipment-edit.$id'
import { Route as AuthenticatedEquipmentDetailIdRouteImport } from './routes/_authenticated/equipment-detail.$id'
import { Route as AuthenticatedStockHistoryTypeIdRouteImport } from './routes/_authenticated/stock-history.$type.$id'
import { Route as AuthenticatedRolesTrainingNewRouteImport } from './routes/_authenticated/roles.training.new'
import { Route as AuthenticatedRolesTrainingIdRouteImport } from './routes/_authenticated/roles.training.$id'
import { Route as AuthenticatedRolesEmployeesNewRouteImport } from './routes/_authenticated/roles.employees.new'
import { Route as AuthenticatedRolesEmployeesIdRouteImport } from './routes/_authenticated/roles.employees.$id'
import { Route as AuthenticatedRolesTrainingPerformanceRecordIdRouteImport } from './routes/_authenticated/roles.training.performance.$recordId'
import { Route as AuthenticatedRolesTrainingIdPerformanceRouteImport } from './routes/_authenticated/roles.training.$id.performance'
import { Route as AuthenticatedRolesTrainingIdEditRouteImport } from './routes/_authenticated/roles.training.$id.edit'
import { Route as AuthenticatedRolesEmployeesIdEditRouteImport } from './routes/_authenticated/roles.employees.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUdiRegistrationRoute =
  AuthenticatedUdiRegistrationRouteImport.update({
    id: '/udi-registration',
    path: '/udi-registration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTraceabilityRoute =
  AuthenticatedTraceabilityRouteImport.update({
    id: '/traceability',
    path: '/traceability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegisterUdiRoute =
  AuthenticatedRegisterUdiRouteImport.update({
    id: '/register-udi',
    path: '/register-udi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRawMaterialsRoute =
  AuthenticatedRawMaterialsRouteImport.update({
    id: '/raw-materials',
    path: '/raw-materials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionPlanningRoute =
  AuthenticatedProductionPlanningRouteImport.update({
    id: '/production-planning',
    path: '/production-planning',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionNewRoute =
  AuthenticatedProductionNewRouteImport.update({
    id: '/production-new',
    path: '/production-new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartsRoute = AuthenticatedPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOtherItemsRoute = AuthenticatedOtherItemsRouteImport.update({
  id: '/other-items',
  path: '/other-items',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectionFormTemplateRoute =
  AuthenticatedInspectionFormTemplateRouteImport.update({
    id: '/inspection-form-template',
    path: '/inspection-form-template',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentNewRoute =
  AuthenticatedEquipmentNewRouteImport.update({
    id: '/equipment-new',
    path: '/equipment-new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnquireSerialRoute =
  AuthenticatedEnquireSerialRouteImport.update({
    id: '/enquire-serial',
    path: '/enquire-serial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBatchRecallRoute =
  AuthenticatedBatchRecallRouteImport.update({
    id: '/batch-recall',
    path: '/batch-recall',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesTrainingRoute =
  AuthenticatedRolesTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedRolesRoute,
  } as any)
const AuthenticatedRolesEmployeesRoute =
  AuthenticatedRolesEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedRolesRoute,
  } as any)
const AuthenticatedProductsBomIdRoute =
  AuthenticatedProductsBomIdRouteImport.update({
    id: '/products-bom/$id',
    path: '/products-bom/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductInspectionProductIdRoute =
  AuthenticatedProductInspectionProductIdRouteImport.update({
    id: '/product-inspection/$productId',
    path: '/product-inspection/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionFormBatchIdRoute =
  AuthenticatedInspectionFormBatchIdRouteImport.update({
    id: '/inspection-form/$batchId',
    path: '/inspection-form/$batchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentEditIdRoute =
  AuthenticatedEquipmentEditIdRouteImport.update({
    id: '/equipment-edit/$id',
    path: '/equipment-edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentDetailIdRoute =
  AuthenticatedEquipmentDetailIdRouteImport.update({
    id: '/equipment-detail/$id',
    path: '/equipment-detail/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockHistoryTypeIdRoute =
  AuthenticatedStockHistoryTypeIdRouteImport.update({
    id: '/stock-history/$type/$id',
    path: '/stock-history/$type/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesTrainingNewRoute =
  AuthenticatedRolesTrainingNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedRolesTrainingRoute,
  } as any)
const AuthenticatedRolesTrainingIdRoute =
  AuthenticatedRolesTrainingIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedRolesTrainingRoute,
  } as any)
const AuthenticatedRolesEmployeesNewRoute =
  AuthenticatedRolesEmployeesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedRolesEmployeesRoute,
  } as any)
const AuthenticatedRolesEmployeesIdRoute =
  AuthenticatedRolesEmployeesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedRolesEmployeesRoute,
  } as any)
const AuthenticatedRolesTrainingPerformanceRecordIdRoute =
  AuthenticatedRolesTrainingPerformanceRecordIdRouteImport.update({
    id: '/performance/$recordId',
    path: '/performance/$recordId',
    getParentRoute: () => AuthenticatedRolesTrainingRoute,
  } as any)
const AuthenticatedRolesTrainingIdPerformanceRoute =
  AuthenticatedRolesTrainingIdPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRolesTrainingIdRoute,
  } as any)
const AuthenticatedRolesTrainingIdEditRoute =
  AuthenticatedRolesTrainingIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedRolesTrainingIdRoute,
  } as any)
const AuthenticatedRolesEmployeesIdEditRoute =
  AuthenticatedRolesEmployeesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedRolesEmployeesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/batch-recall': typeof AuthenticatedBatchRecallRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enquire-serial': typeof AuthenticatedEnquireSerialRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/equipment-new': typeof AuthenticatedEquipmentNewRoute
  '/inspection-form-template': typeof AuthenticatedInspectionFormTemplateRoute
  '/other-items': typeof AuthenticatedOtherItemsRoute
  '/parts': typeof AuthenticatedPartsRoute
  '/production': typeof AuthenticatedProductionRoute
  '/production-new': typeof AuthenticatedProductionNewRoute
  '/production-planning': typeof AuthenticatedProductionPlanningRoute
  '/products': typeof AuthenticatedProductsRoute
  '/raw-materials': typeof AuthenticatedRawMaterialsRoute
  '/register-udi': typeof AuthenticatedRegisterUdiRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles': typeof AuthenticatedRolesRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/traceability': typeof AuthenticatedTraceabilityRoute
  '/udi-registration': typeof AuthenticatedUdiRegistrationRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/equipment-detail/$id': typeof AuthenticatedEquipmentDetailIdRoute
  '/equipment-edit/$id': typeof AuthenticatedEquipmentEditIdRoute
  '/inspection-form/$batchId': typeof AuthenticatedInspectionFormBatchIdRoute
  '/product-inspection/$productId': typeof AuthenticatedProductInspectionProductIdRoute
  '/products-bom/$id': typeof AuthenticatedProductsBomIdRoute
  '/roles/employees': typeof AuthenticatedRolesEmployeesRouteWithChildren
  '/roles/training': typeof AuthenticatedRolesTrainingRouteWithChildren
  '/roles/employees/$id': typeof AuthenticatedRolesEmployeesIdRouteWithChildren
  '/roles/employees/new': typeof AuthenticatedRolesEmployeesNewRoute
  '/roles/training/$id': typeof AuthenticatedRolesTrainingIdRouteWithChildren
  '/roles/training/new': typeof AuthenticatedRolesTrainingNewRoute
  '/stock-history/$type/$id': typeof AuthenticatedStockHistoryTypeIdRoute
  '/roles/employees/$id/edit': typeof AuthenticatedRolesEmployeesIdEditRoute
  '/roles/training/$id/edit': typeof AuthenticatedRolesTrainingIdEditRoute
  '/roles/training/$id/performance': typeof AuthenticatedRolesTrainingIdPerformanceRoute
  '/roles/training/performance/$recordId': typeof AuthenticatedRolesTrainingPerformanceRecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/batch-recall': typeof AuthenticatedBatchRecallRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enquire-serial': typeof AuthenticatedEnquireSerialRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/equipment-new': typeof AuthenticatedEquipmentNewRoute
  '/inspection-form-template': typeof AuthenticatedInspectionFormTemplateRoute
  '/other-items': typeof AuthenticatedOtherItemsRoute
  '/parts': typeof AuthenticatedPartsRoute
  '/production': typeof AuthenticatedProductionRoute
  '/production-new': typeof AuthenticatedProductionNewRoute
  '/production-planning': typeof AuthenticatedProductionPlanningRoute
  '/products': typeof AuthenticatedProductsRoute
  '/raw-materials': typeof AuthenticatedRawMaterialsRoute
  '/register-udi': typeof AuthenticatedRegisterUdiRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles': typeof AuthenticatedRolesRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/traceability': typeof AuthenticatedTraceabilityRoute
  '/udi-registration': typeof AuthenticatedUdiRegistrationRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/equipment-detail/$id': typeof AuthenticatedEquipmentDetailIdRoute
  '/equipment-edit/$id': typeof AuthenticatedEquipmentEditIdRoute
  '/inspection-form/$batchId': typeof AuthenticatedInspectionFormBatchIdRoute
  '/product-inspection/$productId': typeof AuthenticatedProductInspectionProductIdRoute
  '/products-bom/$id': typeof AuthenticatedProductsBomIdRoute
  '/roles/employees': typeof AuthenticatedRolesEmployeesRouteWithChildren
  '/roles/training': typeof AuthenticatedRolesTrainingRouteWithChildren
  '/roles/employees/$id': typeof AuthenticatedRolesEmployeesIdRouteWithChildren
  '/roles/employees/new': typeof AuthenticatedRolesEmployeesNewRoute
  '/roles/training/$id': typeof AuthenticatedRolesTrainingIdRouteWithChildren
  '/roles/training/new': typeof AuthenticatedRolesTrainingNewRoute
  '/stock-history/$type/$id': typeof AuthenticatedStockHistoryTypeIdRoute
  '/roles/employees/$id/edit': typeof AuthenticatedRolesEmployeesIdEditRoute
  '/roles/training/$id/edit': typeof AuthenticatedRolesTrainingIdEditRoute
  '/roles/training/$id/performance': typeof AuthenticatedRolesTrainingIdPerformanceRoute
  '/roles/training/performance/$recordId': typeof AuthenticatedRolesTrainingPerformanceRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/batch-recall': typeof AuthenticatedBatchRecallRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/enquire-serial': typeof AuthenticatedEnquireSerialRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/equipment-new': typeof AuthenticatedEquipmentNewRoute
  '/_authenticated/inspection-form-template': typeof AuthenticatedInspectionFormTemplateRoute
  '/_authenticated/other-items': typeof AuthenticatedOtherItemsRoute
  '/_authenticated/parts': typeof AuthenticatedPartsRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/production-new': typeof AuthenticatedProductionNewRoute
  '/_authenticated/production-planning': typeof AuthenticatedProductionPlanningRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/raw-materials': typeof AuthenticatedRawMaterialsRoute
  '/_authenticated/register-udi': typeof AuthenticatedRegisterUdiRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/traceability': typeof AuthenticatedTraceabilityRoute
  '/_authenticated/udi-registration': typeof AuthenticatedUdiRegistrationRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/_authenticated/equipment-detail/$id': typeof AuthenticatedEquipmentDetailIdRoute
  '/_authenticated/equipment-edit/$id': typeof AuthenticatedEquipmentEditIdRoute
  '/_authenticated/inspection-form/$batchId': typeof AuthenticatedInspectionFormBatchIdRoute
  '/_authenticated/product-inspection/$productId': typeof AuthenticatedProductInspectionProductIdRoute
  '/_authenticated/products-bom/$id': typeof AuthenticatedProductsBomIdRoute
  '/_authenticated/roles/employees': typeof AuthenticatedRolesEmployeesRouteWithChildren
  '/_authenticated/roles/training': typeof AuthenticatedRolesTrainingRouteWithChildren
  '/_authenticated/roles/employees/$id': typeof AuthenticatedRolesEmployeesIdRouteWithChildren
  '/_authenticated/roles/employees/new': typeof AuthenticatedRolesEmployeesNewRoute
  '/_authenticated/roles/training/$id': typeof AuthenticatedRolesTrainingIdRouteWithChildren
  '/_authenticated/roles/training/new': typeof AuthenticatedRolesTrainingNewRoute
  '/_authenticated/stock-history/$type/$id': typeof AuthenticatedStockHistoryTypeIdRoute
  '/_authenticated/roles/employees/$id/edit': typeof AuthenticatedRolesEmployeesIdEditRoute
  '/_authenticated/roles/training/$id/edit': typeof AuthenticatedRolesTrainingIdEditRoute
  '/_authenticated/roles/training/$id/performance': typeof AuthenticatedRolesTrainingIdPerformanceRoute
  '/_authenticated/roles/training/performance/$recordId': typeof AuthenticatedRolesTrainingPerformanceRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alerts'
    | '/batch-recall'
    | '/dashboard'
    | '/enquire-serial'
    | '/equipment'
    | '/equipment-new'
    | '/inspection-form-template'
    | '/other-items'
    | '/parts'
    | '/production'
    | '/production-new'
    | '/production-planning'
    | '/products'
    | '/raw-materials'
    | '/register-udi'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/stock'
    | '/traceability'
    | '/udi-registration'
    | '/vendors'
    | '/equipment-detail/$id'
    | '/equipment-edit/$id'
    | '/inspection-form/$batchId'
    | '/product-inspection/$productId'
    | '/products-bom/$id'
    | '/roles/employees'
    | '/roles/training'
    | '/roles/employees/$id'
    | '/roles/employees/new'
    | '/roles/training/$id'
    | '/roles/training/new'
    | '/stock-history/$type/$id'
    | '/roles/employees/$id/edit'
    | '/roles/training/$id/edit'
    | '/roles/training/$id/performance'
    | '/roles/training/performance/$recordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alerts'
    | '/batch-recall'
    | '/dashboard'
    | '/enquire-serial'
    | '/equipment'
    | '/equipment-new'
    | '/inspection-form-template'
    | '/other-items'
    | '/parts'
    | '/production'
    | '/production-new'
    | '/production-planning'
    | '/products'
    | '/raw-materials'
    | '/register-udi'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/stock'
    | '/traceability'
    | '/udi-registration'
    | '/vendors'
    | '/equipment-detail/$id'
    | '/equipment-edit/$id'
    | '/inspection-form/$batchId'
    | '/product-inspection/$productId'
    | '/products-bom/$id'
    | '/roles/employees'
    | '/roles/training'
    | '/roles/employees/$id'
    | '/roles/employees/new'
    | '/roles/training/$id'
    | '/roles/training/new'
    | '/stock-history/$type/$id'
    | '/roles/employees/$id/edit'
    | '/roles/training/$id/edit'
    | '/roles/training/$id/performance'
    | '/roles/training/performance/$recordId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alerts'
    | '/_authenticated/batch-recall'
    | '/_authenticated/dashboard'
    | '/_authenticated/enquire-serial'
    | '/_authenticated/equipment'
    | '/_authenticated/equipment-new'
    | '/_authenticated/inspection-form-template'
    | '/_authenticated/other-items'
    | '/_authenticated/parts'
    | '/_authenticated/production'
    | '/_authenticated/production-new'
    | '/_authenticated/production-planning'
    | '/_authenticated/products'
    | '/_authenticated/raw-materials'
    | '/_authenticated/register-udi'
    | '/_authenticated/reports'
    | '/_authenticated/roles'
    | '/_authenticated/settings'
    | '/_authenticated/stock'
    | '/_authenticated/traceability'
    | '/_authenticated/udi-registration'
    | '/_authenticated/vendors'
    | '/_authenticated/equipment-detail/$id'
    | '/_authenticated/equipment-edit/$id'
    | '/_authenticated/inspection-form/$batchId'
    | '/_authenticated/product-inspection/$productId'
    | '/_authenticated/products-bom/$id'
    | '/_authenticated/roles/employees'
    | '/_authenticated/roles/training'
    | '/_authenticated/roles/employees/$id'
    | '/_authenticated/roles/employees/new'
    | '/_authenticated/roles/training/$id'
    | '/_authenticated/roles/training/new'
    | '/_authenticated/stock-history/$type/$id'
    | '/_authenticated/roles/employees/$id/edit'
    | '/_authenticated/roles/training/$id/edit'
    | '/_authenticated/roles/training/$id/performance'
    | '/_authenticated/roles/training/performance/$recordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/udi-registration': {
      id: '/_authenticated/udi-registration'
      path: '/udi-registration'
      fullPath: '/udi-registration'
      preLoaderRoute: typeof AuthenticatedUdiRegistrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/traceability': {
      id: '/_authenticated/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof AuthenticatedTraceabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/register-udi': {
      id: '/_authenticated/register-udi'
      path: '/register-udi'
      fullPath: '/register-udi'
      preLoaderRoute: typeof AuthenticatedRegisterUdiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/raw-materials': {
      id: '/_authenticated/raw-materials'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof AuthenticatedRawMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production-planning': {
      id: '/_authenticated/production-planning'
      path: '/production-planning'
      fullPath: '/production-planning'
      preLoaderRoute: typeof AuthenticatedProductionPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production-new': {
      id: '/_authenticated/production-new'
      path: '/production-new'
      fullPath: '/production-new'
      preLoaderRoute: typeof AuthenticatedProductionNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parts': {
      id: '/_authenticated/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof AuthenticatedPartsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/other-items': {
      id: '/_authenticated/other-items'
      path: '/other-items'
      fullPath: '/other-items'
      preLoaderRoute: typeof AuthenticatedOtherItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection-form-template': {
      id: '/_authenticated/inspection-form-template'
      path: '/inspection-form-template'
      fullPath: '/inspection-form-template'
      preLoaderRoute: typeof AuthenticatedInspectionFormTemplateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment-new': {
      id: '/_authenticated/equipment-new'
      path: '/equipment-new'
      fullPath: '/equipment-new'
      preLoaderRoute: typeof AuthenticatedEquipmentNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enquire-serial': {
      id: '/_authenticated/enquire-serial'
      path: '/enquire-serial'
      fullPath: '/enquire-serial'
      preLoaderRoute: typeof AuthenticatedEnquireSerialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batch-recall': {
      id: '/_authenticated/batch-recall'
      path: '/batch-recall'
      fullPath: '/batch-recall'
      preLoaderRoute: typeof AuthenticatedBatchRecallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/training': {
      id: '/_authenticated/roles/training'
      path: '/training'
      fullPath: '/roles/training'
      preLoaderRoute: typeof AuthenticatedRolesTrainingRouteImport
      parentRoute: typeof AuthenticatedRolesRoute
    }
    '/_authenticated/roles/employees': {
      id: '/_authenticated/roles/employees'
      path: '/employees'
      fullPath: '/roles/employees'
      preLoaderRoute: typeof AuthenticatedRolesEmployeesRouteImport
      parentRoute: typeof AuthenticatedRolesRoute
    }
    '/_authenticated/products-bom/$id': {
      id: '/_authenticated/products-bom/$id'
      path: '/products-bom/$id'
      fullPath: '/products-bom/$id'
      preLoaderRoute: typeof AuthenticatedProductsBomIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/product-inspection/$productId': {
      id: '/_authenticated/product-inspection/$productId'
      path: '/product-inspection/$productId'
      fullPath: '/product-inspection/$productId'
      preLoaderRoute: typeof AuthenticatedProductInspectionProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection-form/$batchId': {
      id: '/_authenticated/inspection-form/$batchId'
      path: '/inspection-form/$batchId'
      fullPath: '/inspection-form/$batchId'
      preLoaderRoute: typeof AuthenticatedInspectionFormBatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment-edit/$id': {
      id: '/_authenticated/equipment-edit/$id'
      path: '/equipment-edit/$id'
      fullPath: '/equipment-edit/$id'
      preLoaderRoute: typeof AuthenticatedEquipmentEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment-detail/$id': {
      id: '/_authenticated/equipment-detail/$id'
      path: '/equipment-detail/$id'
      fullPath: '/equipment-detail/$id'
      preLoaderRoute: typeof AuthenticatedEquipmentDetailIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-history/$type/$id': {
      id: '/_authenticated/stock-history/$type/$id'
      path: '/stock-history/$type/$id'
      fullPath: '/stock-history/$type/$id'
      preLoaderRoute: typeof AuthenticatedStockHistoryTypeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/training/new': {
      id: '/_authenticated/roles/training/new'
      path: '/new'
      fullPath: '/roles/training/new'
      preLoaderRoute: typeof AuthenticatedRolesTrainingNewRouteImport
      parentRoute: typeof AuthenticatedRolesTrainingRoute
    }
    '/_authenticated/roles/training/$id': {
      id: '/_authenticated/roles/training/$id'
      path: '/$id'
      fullPath: '/roles/training/$id'
      preLoaderRoute: typeof AuthenticatedRolesTrainingIdRouteImport
      parentRoute: typeof AuthenticatedRolesTrainingRoute
    }
    '/_authenticated/roles/employees/new': {
      id: '/_authenticated/roles/employees/new'
      path: '/new'
      fullPath: '/roles/employees/new'
      preLoaderRoute: typeof AuthenticatedRolesEmployeesNewRouteImport
      parentRoute: typeof AuthenticatedRolesEmployeesRoute
    }
    '/_authenticated/roles/employees/$id': {
      id: '/_authenticated/roles/employees/$id'
      path: '/$id'
      fullPath: '/roles/employees/$id'
      preLoaderRoute: typeof AuthenticatedRolesEmployeesIdRouteImport
      parentRoute: typeof AuthenticatedRolesEmployeesRoute
    }
    '/_authenticated/roles/training/performance/$recordId': {
      id: '/_authenticated/roles/training/performance/$recordId'
      path: '/performance/$recordId'
      fullPath: '/roles/training/performance/$recordId'
      preLoaderRoute: typeof AuthenticatedRolesTrainingPerformanceRecordIdRouteImport
      parentRoute: typeof AuthenticatedRolesTrainingRoute
    }
    '/_authenticated/roles/training/$id/performance': {
      id: '/_authenticated/roles/training/$id/performance'
      path: '/performance'
      fullPath: '/roles/training/$id/performance'
      preLoaderRoute: typeof AuthenticatedRolesTrainingIdPerformanceRouteImport
      parentRoute: typeof AuthenticatedRolesTrainingIdRoute
    }
    '/_authenticated/roles/training/$id/edit': {
      id: '/_authenticated/roles/training/$id/edit'
      path: '/edit'
      fullPath: '/roles/training/$id/edit'
      preLoaderRoute: typeof AuthenticatedRolesTrainingIdEditRouteImport
      parentRoute: typeof AuthenticatedRolesTrainingIdRoute
    }
    '/_authenticated/roles/employees/$id/edit': {
      id: '/_authenticated/roles/employees/$id/edit'
      path: '/edit'
      fullPath: '/roles/employees/$id/edit'
      preLoaderRoute: typeof AuthenticatedRolesEmployeesIdEditRouteImport
      parentRoute: typeof AuthenticatedRolesEmployeesIdRoute
    }
  }
}

interface AuthenticatedRolesEmployeesIdRouteChildren {
  AuthenticatedRolesEmployeesIdEditRoute: typeof AuthenticatedRolesEmployeesIdEditRoute
}

const AuthenticatedRolesEmployeesIdRouteChildren: AuthenticatedRolesEmployeesIdRouteChildren =
  {
    AuthenticatedRolesEmployeesIdEditRoute:
      AuthenticatedRolesEmployeesIdEditRoute,
  }

const AuthenticatedRolesEmployeesIdRouteWithChildren =
  AuthenticatedRolesEmployeesIdRoute._addFileChildren(
    AuthenticatedRolesEmployeesIdRouteChildren,
  )

interface AuthenticatedRolesEmployeesRouteChildren {
  AuthenticatedRolesEmployeesIdRoute: typeof AuthenticatedRolesEmployeesIdRouteWithChildren
  AuthenticatedRolesEmployeesNewRoute: typeof AuthenticatedRolesEmployeesNewRoute
}

const AuthenticatedRolesEmployeesRouteChildren: AuthenticatedRolesEmployeesRouteChildren =
  {
    AuthenticatedRolesEmployeesIdRoute:
      AuthenticatedRolesEmployeesIdRouteWithChildren,
    AuthenticatedRolesEmployeesNewRoute: AuthenticatedRolesEmployeesNewRoute,
  }

const AuthenticatedRolesEmployeesRouteWithChildren =
  AuthenticatedRolesEmployeesRoute._addFileChildren(
    AuthenticatedRolesEmployeesRouteChildren,
  )

interface AuthenticatedRolesTrainingIdRouteChildren {
  AuthenticatedRolesTrainingIdEditRoute: typeof AuthenticatedRolesTrainingIdEditRoute
  AuthenticatedRolesTrainingIdPerformanceRoute: typeof AuthenticatedRolesTrainingIdPerformanceRoute
}

const AuthenticatedRolesTrainingIdRouteChildren: AuthenticatedRolesTrainingIdRouteChildren =
  {
    AuthenticatedRolesTrainingIdEditRoute:
      AuthenticatedRolesTrainingIdEditRoute,
    AuthenticatedRolesTrainingIdPerformanceRoute:
      AuthenticatedRolesTrainingIdPerformanceRoute,
  }

const AuthenticatedRolesTrainingIdRouteWithChildren =
  AuthenticatedRolesTrainingIdRoute._addFileChildren(
    AuthenticatedRolesTrainingIdRouteChildren,
  )

interface AuthenticatedRolesTrainingRouteChildren {
  AuthenticatedRolesTrainingIdRoute: typeof AuthenticatedRolesTrainingIdRouteWithChildren
  AuthenticatedRolesTrainingNewRoute: typeof AuthenticatedRolesTrainingNewRoute
  AuthenticatedRolesTrainingPerformanceRecordIdRoute: typeof AuthenticatedRolesTrainingPerformanceRecordIdRoute
}

const AuthenticatedRolesTrainingRouteChildren: AuthenticatedRolesTrainingRouteChildren =
  {
    AuthenticatedRolesTrainingIdRoute:
      AuthenticatedRolesTrainingIdRouteWithChildren,
    AuthenticatedRolesTrainingNewRoute: AuthenticatedRolesTrainingNewRoute,
    AuthenticatedRolesTrainingPerformanceRecordIdRoute:
      AuthenticatedRolesTrainingPerformanceRecordIdRoute,
  }

const AuthenticatedRolesTrainingRouteWithChildren =
  AuthenticatedRolesTrainingRoute._addFileChildren(
    AuthenticatedRolesTrainingRouteChildren,
  )

interface AuthenticatedRolesRouteChildren {
  AuthenticatedRolesEmployeesRoute: typeof AuthenticatedRolesEmployeesRouteWithChildren
  AuthenticatedRolesTrainingRoute: typeof AuthenticatedRolesTrainingRouteWithChildren
}

const AuthenticatedRolesRouteChildren: AuthenticatedRolesRouteChildren = {
  AuthenticatedRolesEmployeesRoute:
    AuthenticatedRolesEmployeesRouteWithChildren,
  AuthenticatedRolesTrainingRoute: AuthenticatedRolesTrainingRouteWithChildren,
}

const AuthenticatedRolesRouteWithChildren =
  AuthenticatedRolesRoute._addFileChildren(AuthenticatedRolesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedBatchRecallRoute: typeof AuthenticatedBatchRecallRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnquireSerialRoute: typeof AuthenticatedEnquireSerialRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedEquipmentNewRoute: typeof AuthenticatedEquipmentNewRoute
  AuthenticatedInspectionFormTemplateRoute: typeof AuthenticatedInspectionFormTemplateRoute
  AuthenticatedOtherItemsRoute: typeof AuthenticatedOtherItemsRoute
  AuthenticatedPartsRoute: typeof AuthenticatedPartsRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProductionNewRoute: typeof AuthenticatedProductionNewRoute
  AuthenticatedProductionPlanningRoute: typeof AuthenticatedProductionPlanningRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedRawMaterialsRoute: typeof AuthenticatedRawMaterialsRoute
  AuthenticatedRegisterUdiRoute: typeof AuthenticatedRegisterUdiRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedTraceabilityRoute: typeof AuthenticatedTraceabilityRoute
  AuthenticatedUdiRegistrationRoute: typeof AuthenticatedUdiRegistrationRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
  AuthenticatedEquipmentDetailIdRoute: typeof AuthenticatedEquipmentDetailIdRoute
  AuthenticatedEquipmentEditIdRoute: typeof AuthenticatedEquipmentEditIdRoute
  AuthenticatedInspectionFormBatchIdRoute: typeof AuthenticatedInspectionFormBatchIdRoute
  AuthenticatedProductInspectionProductIdRoute: typeof AuthenticatedProductInspectionProductIdRoute
  AuthenticatedProductsBomIdRoute: typeof AuthenticatedProductsBomIdRoute
  AuthenticatedStockHistoryTypeIdRoute: typeof AuthenticatedStockHistoryTypeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedBatchRecallRoute: AuthenticatedBatchRecallRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnquireSerialRoute: AuthenticatedEnquireSerialRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedEquipmentNewRoute: AuthenticatedEquipmentNewRoute,
  AuthenticatedInspectionFormTemplateRoute:
    AuthenticatedInspectionFormTemplateRoute,
  AuthenticatedOtherItemsRoute: AuthenticatedOtherItemsRoute,
  AuthenticatedPartsRoute: AuthenticatedPartsRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProductionNewRoute: AuthenticatedProductionNewRoute,
  AuthenticatedProductionPlanningRoute: AuthenticatedProductionPlanningRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedRawMaterialsRoute: AuthenticatedRawMaterialsRoute,
  AuthenticatedRegisterUdiRoute: AuthenticatedRegisterUdiRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedTraceabilityRoute: AuthenticatedTraceabilityRoute,
  AuthenticatedUdiRegistrationRoute: AuthenticatedUdiRegistrationRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
  AuthenticatedEquipmentDetailIdRoute: AuthenticatedEquipmentDetailIdRoute,
  AuthenticatedEquipmentEditIdRoute: AuthenticatedEquipmentEditIdRoute,
  AuthenticatedInspectionFormBatchIdRoute:
    AuthenticatedInspectionFormBatchIdRoute,
  AuthenticatedProductInspectionProductIdRoute:
    AuthenticatedProductInspectionProductIdRoute,
  AuthenticatedProductsBomIdRoute: AuthenticatedProductsBomIdRoute,
  AuthenticatedStockHistoryTypeIdRoute: AuthenticatedStockHistoryTypeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
